# Generated by Django 4.0 on 2022-12-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'catogeries'},
        ),
    ]
