# Generated by Django 4.0 on 2022-12-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_alter_product_options_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
