# Generated by Django 4.0 on 2022-12-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0012_remove_product_in_stock_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default='product', max_length=255),
            preserve_default=False,
        ),
    ]
