# Generated by Django 4.0 on 2022-12-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0013_product_in_stock_product_slug_productcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
