# Generated by Django 4.0 on 2022-12-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0014_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='categoryName',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
