# Generated by Django 4.0 on 2022-12-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0017_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categeoy',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
