# Generated by Django 4.0 on 2022-12-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0019_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categeoy',
            new_name='category',
        ),
    ]
