# Generated by Django 4.0 on 2022-12-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0020_rename_categeoy_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='media/j1.png', upload_to='media/'),
        ),
    ]
