# Generated by Django 4.0 on 2022-12-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0021_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
