# Generated by Django 4.0 on 2023-01-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Article', '0023_alter_customeraddress_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='phase_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customer_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShoppingPhase',
        ),
    ]
